"""
Configure CoChat's own assistants (General, Company Rules, Oracle EBS
Assistant) and the background Task Model in Open WebUI. The EBS Analyst /
Support / Finance Controller models are configured separately by
configure_openwebui_ebs_analyst.py.

Every assistant is published as two variants so users can pick by cost:

    General               Qwen Local (qwen3:14b on the AI server) | Haiku 4.5
    Company Rules         Qwen Local                              | Haiku 4.5
    Oracle EBS Assistant  Sonnet 5                                | Haiku 4.5

Existing presets are recognised by role, not id (dev and prod ids differ):
presets whose id starts with "cochat-" and whose name/tools identify the
family. Within a family a preset already on the variant's model family keeps
its id (so its chat history stays attached); a leftover preset is repurposed
for a variant nobody holds yet; anything still left over (e.g. the Opus
general model) is deactivated, not deleted. Every variant gets the union of
the family's access grants, so nobody loses sight of an assistant because the
preset they used was retired.

Task Model: titles, tags, follow-up suggestions and search/retrieval queries
were generated by whichever model the chat used — an Opus chat paid Opus
rates for its own title. They now run on a private preset over qwen3:14b with
thinking off. Every qwen3:14b preset shares one num_ctx so Ollama keeps a
single copy of the model loaded instead of reloading it per preset.

Tool-using presets are set to native function calling. In Open WebUI's
default mode the TASK model decides which tool to call, which would hand tool
selection for the Oracle EBS / Company Rules assistants to the local model.

Run inside the backend container (env OPENWEBUI_BASE_URL, OPENWEBUI_API_KEY):

    docker exec ckdo_backend python scripts/configure_openwebui_cochat_models.py          # plan only
    docker exec ckdo_backend python scripts/configure_openwebui_cochat_models.py --apply
"""
import argparse
import json
import os
import sys

import httpx

QWEN = "qwen3:14b"
QWEN_CTX = 16384
HAIKU = "claude-haiku-4-5-20251001"
SONNET = "claude-sonnet-5"
TASK_MODEL_ID = "cochat-task-model"

DESC_QWEN = " Runs on the company's own AI server (Qwen3 14B): no usage cost and nothing leaves the network, " \
            "but slower and less precise than Claude on complex questions."
DESC_HAIKU = " Runs on Claude Haiku 4.5: fast and accurate; billed per use at the lowest Claude rate."
DESC_SONNET = " Runs on Claude Sonnet 5: stronger reasoning for multi-step questions; about twice the cost of Haiku."

# family -> (name, description, [(variant label, base model, id slug, description tail)])
FAMILIES = {
    "general": ("General", "General-purpose assistant for writing, summarising, translating and everyday questions.",
                [("Qwen Local", QWEN, "qwen-local", DESC_QWEN), ("Haiku 4.5", HAIKU, "haiku", DESC_HAIKU)]),
    "company-rules": ("Company Rules", "Answers questions about company rules, policies and SOP documents, "
                      "citing the document it used.",
                      [("Qwen Local", QWEN, "qwen-local",
                        DESC_QWEN + " Document look-ups still run through the dashboard."),
                       ("Haiku 4.5", HAIKU, "haiku", DESC_HAIKU)]),
    "oracle-ebs": ("Oracle EBS Assistant", "Answers questions about Oracle EBS data (sales, purchasing, inventory, "
                   "production, finance, headcount, IT infrastructure) through the dashboard.",
                   [("Sonnet 5", SONNET, "sonnet-5", DESC_SONNET), ("Haiku 4.5", HAIKU, "haiku", DESC_HAIKU)]),
}


def family_of(m: dict) -> str | None:
    if not m["id"].startswith("cochat-") or m["id"] == TASK_MODEL_ID:
        return None
    name = (m.get("name") or "").lower()
    tools = (m.get("meta") or {}).get("toolIds") or []
    if "oracle_ebs_query" in tools and "oracle ebs" in name:
        return "oracle-ebs"
    if "oracle_ebs_query" in tools and "comp" in name:
        return "company-rules"
    if not tools:
        return "general"
    return None


def same_line(base: str, target: str) -> bool:
    """Is `base` the same model line as `target` (any Qwen / Haiku / Sonnet)?"""
    base = (base or "").lower()
    for word in ("qwen", "haiku", "sonnet"):
        if word in target:
            return word in base
    return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="make the changes (default: print the plan only)")
    args = ap.parse_args()

    base = os.environ["OPENWEBUI_BASE_URL"].rstrip("/")
    c = httpx.Client(base_url=f"{base}/api/v1", headers={"Authorization": f"Bearer {os.environ['OPENWEBUI_API_KEY']}"},
                     timeout=60)

    def call(method, path, **kw):
        r = c.request(method, path, **kw)
        if r.status_code >= 400:
            raise SystemExit(f"{method} {path} -> {r.status_code}: {r.text[:400]}")
        return r.json() if r.content else None

    listing = call("GET", "/models/list")
    presets = listing.get("items", listing) if isinstance(listing, dict) else listing
    print(f"Open WebUI: {base} — {len(presets)} preset(s)")

    writes = []   # (action, body)
    for fam, (fname, fdesc, variants) in FAMILIES.items():
        members = [m for m in presets if family_of(m) == fam]
        grants, seen = [], set()
        for m in members:
            for g in m.get("access_grants") or []:
                k = (g.get("principal_type"), g.get("principal_id"), g.get("permission"))
                if k not in seen:
                    seen.add(k)
                    grants.append({"principal_type": k[0], "principal_id": k[1], "permission": k[2]})

        # Keep ids where the model line already matches, repurpose leftovers, retire the rest.
        assigned, free = {}, list(members)
        for label, model, _, _ in variants:
            hit = next((m for m in free if same_line(m.get("base_model_id"), model)), None)
            if hit:
                assigned[label] = hit
                free.remove(hit)
        for label, *_ in variants:
            if label not in assigned and free:
                assigned[label] = free.pop(0)
        ref = members[0] if members else {"meta": {}, "params": {}}

        for label, model, slug, tail in variants:
            src = assigned.get(label)
            meta = json.loads(json.dumps((src or ref).get("meta") or {}))
            meta["description"] = fdesc + tail
            if fam != "general":
                # Internal data: web search only adds tokens and noise by default.
                meta["defaultFeatureIds"] = [f for f in (meta.get("defaultFeatureIds") or []) if f != "web_search"]
            params = {k: v for k, v in ((src or ref).get("params") or {}).items() if k not in ("num_ctx", "think")}
            if model == QWEN:
                params["num_ctx"] = QWEN_CTX
                params.pop("max_tokens", None)
                # qwen3:14b is text-only; an image upload would fail mid-chat.
                meta["capabilities"] = {**(meta.get("capabilities") or {}), "vision": False}
            if meta.get("toolIds"):
                params["function_calling"] = "native"
            body = {
                "id": src["id"] if src else f"cochat-{fam}-{slug}",
                "name": f"{fname} ({label})",
                "base_model_id": model,
                "meta": meta,
                "params": params,
                "access_grants": grants,
                "is_active": True,
            }
            was = f"was '{src.get('name')}' on {src.get('base_model_id')}" if src else "new"
            writes.append(("update" if src else "create", body))
            print(f"  [{fam}] {body['id']:40} -> {body['name']:34} base={model:28} ({was}); "
                  f"grants={len(grants)} defaults={meta.get('defaultFeatureIds')} params={params}")
        for m in free:
            body = {k: m.get(k) for k in ("id", "name", "base_model_id", "meta", "params", "access_grants")}
            body["is_active"] = False
            writes.append(("update", body))
            print(f"  [{fam}] {m['id']:40} -> DEACTIVATE '{m.get('name')}' ({m.get('base_model_id')})")

    task = {
        "id": TASK_MODEL_ID,
        "name": "Task Model (Qwen Local)",
        "base_model_id": QWEN,
        "meta": {"description": "Background tasks only: chat titles, tags, follow-up suggestions and search "
                                "queries. Runs on the company's AI server so these cost nothing.",
                 "profile_image_url": "/static/favicon.png", "capabilities": {}},
        "params": {"num_ctx": QWEN_CTX, "think": False},
        "access_grants": [],   # admins only; tasks run server-side
        "is_active": True,
    }
    existing_ids = {m["id"] for m in presets}
    writes.append(("update" if TASK_MODEL_ID in existing_ids else "create", task))
    print(f"  [task] {TASK_MODEL_ID} on {QWEN} (think off) -> TASK_MODEL and TASK_MODEL_EXTERNAL")

    if not args.apply:
        print("\nPlan only. Re-run with --apply to make these changes.")
        return

    for action, body in writes:
        if action == "update":
            call("POST", f"/models/model/update?id={body['id']}", json=body)
        else:
            call("POST", "/models/create", json=body)
    cfg = call("GET", "/tasks/config")
    cfg.update({"TASK_MODEL": TASK_MODEL_ID, "TASK_MODEL_EXTERNAL": TASK_MODEL_ID})
    call("POST", "/tasks/config/update", json=cfg)
    got = call("GET", "/tasks/config")
    print(f"\nApplied {len(writes)} model change(s); task model = {got.get('TASK_MODEL')} / "
          f"{got.get('TASK_MODEL_EXTERNAL')}")


if __name__ == "__main__":
    sys.exit(main())
